# Generated by Django 5.0.1 on 2024-02-02 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppFamilia", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="familia",
            name="edad",
            field=models.IntegerField(null=True),
        ),
    ]
